# Generated by Django 5.2.7 on 2025-10-30 19:57

import core.models
import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_resumeupload_result_json_resumeanalysis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="latexresume",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=core.storage_backends.PrivateMediaStorage(),
                upload_to="latex_resumes/",
            ),
        ),
        migrations.AlterField(
            model_name="resumeupload",
            name="file",
            field=models.FileField(
                storage=core.storage_backends.PrivateMediaStorage(),
                upload_to=core.models.private_resume_path,
            ),
        ),
    ]
